const CREATED_COLUMNS = [ 'FECHA DE CREACION', 'CREADO POR' ];

export const FOLDER_COLUMNS = [
    'NOMBRE',
    'LOCALIDAD',
    'MUNICIPIO',
    'RUTA',
    'LIDER',
    'GRUPO',
    ...CREATED_COLUMNS
]

export const ROUTE_COLUMNS = ['NOMBRE', 'ACTIVO', ...CREATED_COLUMNS];
export const TOWN_COLUMNS = ['LOCALIDAD', 'MUNICIPIO', ...CREATED_COLUMNS];
export const MUNICIPALITY_COLUMNS = ['NOMBRES', ...CREATED_COLUMNS];
export const AGENT_COLUMNS = ['AGENTE', 'RUTA', 'FECHA DE ASIGNACION', ...CREATED_COLUMNS];
export const USER_COLUMNS = [
    'USUARIO', 
    'NOMBRE', 
    'CORREO ELECTRONICO', 
    'DIRECCION', 
    'SEXO', 
    'ROLE', 
    'ACTIVO'
];
export const ROLE_COLUMNS = ['ROLE'];
export const PERMISSION_COLUMNS = [
    'PERMISO', 
    'DESCRIPCION', 
    'ROLE',
    'ASIGNADO', 
    'MODULO', 
];
export const LEADER_COLUMNS = [
    'NOMBRE', 
    'CURP',
    'DIRECCION', 
    'FECHA DE ANIVERSARIO', 
    'FECHA DE CUMPLEAÑOS', 
    'CARPETA',
    'ACTIVO' ,
    ...CREATED_COLUMNS
];
export const CREDIT_COLUMNS = [
    'NOMBRE CLIENTE',
    'DIRECCION CLIENTE',
    'REFERENCIA CLIENTE',
    'CURP CLIENTE',
    'NOMBRE AVAL',
    'DIRECCION AVAL',
    'REFERENCIA AVAL',
    'CURP AVAL',
    'CARPETA',
    'LOCALIDAD',
    'MUNICIPIO',
    'RUTA',
    'GROUP',
    'RENOVACION',
    'CANTIDAD',
    'PAGO SEMANAL',
    'CANTIDAD DE PAGOS',
    'DEUDA ACTUAL',
    'ESTATUS',
    'FECHA DE ALTA',
    'SIGUIENTE PAGO',
    'ULTIMO PAGO',
    ...CREATED_COLUMNS
];
export const PAYMENT_COLUMNS = [
    'NOMBRE CLIENTE',
    'CURP CLIENTE',
    'NOMBRE AVAL',
    'CURP AVAL',
    'AGENTE',
    'DEUDA ACTUAL',
    'SIGUIENTE PAGO',
    'ULTIMO PAGO',
    'ESTATUS CREDITO',
    'CARPETA',
    'LOCALIDAD',
    'MUNICIPIO',
    'RUTA',
    'GROUP',
    'PAGO',
    'FECHA DE PAGO',
    'FOLIO',
    'NOTAS',
    'ESTATUS PAGO',
    ...CREATED_COLUMNS
];



